//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRON_PROGRAMMER_BOT_Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IRON_PROGRAMMER_BOT_Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите дату.
        /// </summary>
        public static string AppointRegisterDatePageText {
            get {
                return ResourceManager.GetString("AppointRegisterDatePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите время.
        /// </summary>
        public static string AppointRegisterTimePageText {
            get {
                return ResourceManager.GetString("AppointRegisterTimePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для авторизации, введи номер телефона и пароль через пробел или нажмите кнопку &lt;b&gt;Зарегистрироваться&lt;/b&gt;.
        /// </summary>
        public static string AuthorizationPageText {
            get {
                return ResourceManager.GetString("AuthorizationPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введи номер телефона в формате:
        ///&lt;i&gt;7xxx-xxx-xx-xx&lt;/i&gt; и мы тебе обязательно перезвоним!!!.
        /// </summary>
        public static string ConsultationPageText {
            get {
                return ResourceManager.GetString("ConsultationPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Адрес:&lt;/b&gt; &lt;i&gt;улица Декабристов, 17, г. Москва, 127566&lt;/i&gt;
        ///&lt;b&gt;Телефон:&lt;/b&gt; &lt;i&gt;7(495)201-40-45&lt;/i&gt;.
        /// </summary>
        public static string ContactPageText {
            get {
                return ResourceManager.GetString("ContactPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите ФИО специалиста.
        /// </summary>
        public static string DoctorsNamePageText {
            get {
                return ResourceManager.GetString("DoctorsNamePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите тип специалиста.
        /// </summary>
        public static string DoctorsTypePageText {
            get {
                return ResourceManager.GetString("DoctorsTypePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Неверный формат ввода&lt;/b&gt;.
        /// </summary>
        public static string IncorrectInputFormatText {
            get {
                return ResourceManager.GetString("IncorrectInputFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Неверный номер телефона или пароль!!!&lt;/b&gt;.
        /// </summary>
        public static string IncorrectUserAuthorizationDataText {
            get {
                return ResourceManager.GetString("IncorrectUserAuthorizationDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Неверный формат номера!!!&lt;/b&gt;.
        /// </summary>
        public static string IncorrectUserNumberText {
            get {
                return ResourceManager.GetString("IncorrectUserNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PersonalAccountPagePhoto {
            get {
                object obj = ResourceManager.GetObject("PersonalAccountPagePhoto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для регистрации, введи номер телефона в формате: &lt;b&gt;79995553322, имя и пароль через пробелы&lt;/b&gt;.
        /// </summary>
        public static string RegisterPageText {
            get {
                return ResourceManager.GetString("RegisterPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите текст отзыва.
        /// </summary>
        public static string ReviewFormPageText {
            get {
                return ResourceManager.GetString("ReviewFormPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Здесь будут отзывы о поликлинике и специалистах&lt;/b&gt;.
        /// </summary>
        public static string ReviewsPageText {
            get {
                return ResourceManager.GetString("ReviewsPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i&gt;Здесь будет информация специалистах&lt;/i&gt;.
        /// </summary>
        public static string SpecialistPageText {
            get {
                return ResourceManager.GetString("SpecialistPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] StartPagePhoto {
            get {
                object obj = ResourceManager.GetObject("StartPagePhoto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рады видеть тебя в нашей поликлинике😊
        ///Задай свой вопрос и я тебе обязательно отвечу!
        ///Хочешь записаться на приём или посмотреть отзывы?
        ///Нажми одну из кнопок ниже - я отвечу и помогу тебе😉.
        /// </summary>
        public static string StartPageText {
            get {
                return ResourceManager.GetString("StartPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звонок успешно заказан!!!.
        /// </summary>
        public static string SuccessCallRequestText {
            get {
                return ResourceManager.GetString("SuccessCallRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзыв успешно отправлен!!!.
        /// </summary>
        public static string SuccessReviewFormPageText {
            get {
                return ResourceManager.GetString("SuccessReviewFormPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записи на приём отсутствуют.
        /// </summary>
        public static string UserAppointPageText {
            get {
                return ResourceManager.GetString("UserAppointPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Пользователь с таким номером уже существует!&lt;/b&gt;.
        /// </summary>
        public static string UserExistErrorText {
            get {
                return ResourceManager.GetString("UserExistErrorText", resourceCulture);
            }
        }
    }
}
